In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
data=pd.read_csv("knn_csv.csv")

In [12]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
print(x)
print(y)

[[158  58]
 [158  59]
 [158  63]
 [160  59]
 [160  60]
 [163  60]
 [163  61]
 [160  64]
 [163  64]
 [165  61]
 [165  62]
 [165  65]
 [168  62]
 [168  63]
 [168  66]
 [170  63]
 [170  64]
 [170  68]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L']


In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]


In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
print(x_test)
print(y_test)
print(x_train)
print(y_train)

[[163  60]
 [168  63]
 [158  63]
 [165  61]
 [170  63]]
[1 0 1 0 0]
[[170  64]
 [168  62]
 [160  60]
 [168  66]
 [163  64]
 [163  61]
 [165  62]
 [165  65]
 [170  68]
 [160  64]
 [158  59]
 [158  58]
 [160  59]]
[0 0 1 0 0 1 0 0 0 0 1 1 1]


In [25]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x_train)
y=sc.fit_transform(x_test)
print(x)
print(y)

[[ 1.51025441  0.53074489]
 [ 1.03139326 -0.15922347]
 [-0.88405136 -0.84919183]
 [ 1.03139326  1.22071325]
 [-0.16575963  0.53074489]
 [-0.16575963 -0.50420765]
 [ 0.31310152 -0.15922347]
 [ 0.31310152  0.87572907]
 [ 1.51025441  1.91068161]
 [-0.88405136  0.53074489]
 [-1.36291252 -1.19417601]
 [-1.36291252 -1.53916019]
 [-0.88405136 -1.19417601]]
[[-0.43201382 -1.58113883]
 [ 0.76802458  0.79056942]
 [-1.63205223  0.79056942]
 [ 0.04800154 -0.79056942]
 [ 1.24803994  0.79056942]]


In [26]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
kn.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
print(kn.predict(sc.transform([[161,61]])))

[1]
